In [37]:
import random
import numpy as np

# Create a table (i.e. a 2d array) of size M x N filled with random integers between 1 and 100, where 1 < N < 40 and 1 < M < 50.
while True:
    input_n = input("Enter N (1<N<40): ")
    input_m = input("Enter M (1<M<50): ")
    try:
        n = int(input_n)
        m = int(input_m)
    except ValueError:
        print("Integers only, please.")
        continue
    if not(1<n<40 and 1<m<50):
        print("At least one number out of range.")
        continue
    break

# Fill table with random numbers
arr = np.random.randint(0, 101, size=(m,n))
print("Entire array: \n", arr)

# Third row
print("Third row: ", arr[2:3])
# Third column
print("Third column: ", arr[:,2])
# Set all last row elements to 7
arr[-1] = 7
print("Last row set to 7: \n", arr)
# Set last column elements to sum of first 2 columns 
arr[:,-1] = np.sum(arr[:,:2], axis = 1)
print("Last column is sum of first 2: \n", arr) 

Entire array: 
 [[ 80  24  61  88  58]
 [ 46  45  39  19 100]
 [ 74  59  57 100  64]
 [  6  19  84  93  46]]
Third row:  [[ 74  59  57 100  64]]
Third column:  [61 39 57 84]
Last row set to 7: 
 [[ 80  24  61  88  58]
 [ 46  45  39  19 100]
 [ 74  59  57 100  64]
 [  7   7   7   7   7]]
Last column is sum of first 2: 
 [[ 80  24  61  88 104]
 [ 46  45  39  19  91]
 [ 74  59  57 100 133]
 [  7   7   7   7  14]]
